#ifndef __INC_AFFECT_H
#define __INC_AFFECT_H

class CAffect
{
public:
	DWORD	dwType;
	BYTE    bApplyOn;
	long    lApplyValue;
	DWORD   dwFlag;
	long	lDuration;
	long	lSPCost;

	static CAffect* Acquire();
	static void Release(CAffect* p);
};

enum EAffectTypes
{
	AFFECT_NONE,

	AFFECT_MOV_SPEED = 200,
	AFFECT_ATT_SPEED,
	AFFECT_ATT_GRADE,
	AFFECT_INVISIBILITY,
	AFFECT_STR,
	AFFECT_DEX,			// 205
	AFFECT_CON,
	AFFECT_INT,
	AFFECT_FISH_MIND_PILL,

	AFFECT_POISON,
	AFFECT_STUN,		// 210
	AFFECT_SLOW,
	AFFECT_DUNGEON_READY,
	AFFECT_DUNGEON_UNIQUE,

	AFFECT_BUILDING,
	AFFECT_REVIVE_INVISIBLE,	// 215
	AFFECT_FIRE,
	AFFECT_CAST_SPEED,
	AFFECT_HP_RECOVER_CONTINUE,
	AFFECT_SP_RECOVER_CONTINUE,

	AFFECT_POLYMORPH,		// 220
	AFFECT_MOUNT,

	AFFECT_WAR_FLAG,		// 222

	AFFECT_BLOCK_CHAT,		// 223
	AFFECT_CHINA_FIREWORK,

	AFFECT_BOW_DISTANCE,	// 225
	AFFECT_DEF_GRADE,		// 226
#ifdef ENABLE_GROWTH_PET_SYSTEM
	AFFECT_PET,
#endif

	AFFECT_WIND_SHOES = 232,

	AFFECT_PREMIUM_START = 500,
	AFFECT_EXP_BONUS = 500,
	AFFECT_ITEM_BONUS = 501,
	AFFECT_SAFEBOX = 502,
	AFFECT_AUTOLOOT = 503,
	AFFECT_FISH_MIND = 504,
	AFFECT_MARRIAGE_FAST = 505,
	AFFECT_GOLD_BONUS = 506,
	AFFECT_PREMIUM_END = 509,

	AFFECT_MALL = 510,
	AFFECT_NO_DEATH_PENALTY = 511,
	AFFECT_SKILL_BOOK_BONUS = 512,
	AFFECT_SKILL_NO_BOOK_DELAY = 513,

	AFFECT_HAIR = 514,
	AFFECT_COLLECT = 515,
	AFFECT_EXP_BONUS_EURO_FREE = 516, // °æÇèÀÇ ¹ÝÁö (À¯·´ ¹öÀü 14 ·¹º§ ÀÌÇÏ ±âº» È¿°ú)
	AFFECT_EXP_BONUS_EURO_FREE_UNDER_15 = 517,
	AFFECT_UNIQUE_ABILITY = 518,

	AFFECT_CUBE_1,
	AFFECT_CUBE_2,
	AFFECT_CUBE_3,
	AFFECT_CUBE_4,
	AFFECT_CUBE_5,
	AFFECT_CUBE_6,
	AFFECT_CUBE_7,
	AFFECT_CUBE_8,
	AFFECT_CUBE_9,
	AFFECT_CUBE_10,
	AFFECT_CUBE_11,
	AFFECT_CUBE_12,

	AFFECT_BLEND,

	AFFECT_HORSE_NAME,
	AFFECT_MOUNT_BONUS,

#ifdef ENABLE_GROWTH_PET_SYSTEM
	AFFECT_NEW_PET = 559,
#endif

	AFFECT_AUTO_HP_RECOVERY = 534,
	AFFECT_AUTO_SP_RECOVERY = 535,

	AFFECT_DRAGON_SOUL_QUALIFIED = 540,
	AFFECT_DRAGON_SOUL_DECK_0 = 541,
	AFFECT_DRAGON_SOUL_DECK_1 = 542,

	AFFECT_RAMADAN_ABILITY = 300,
	AFFECT_RAMADAN_RING = 301,

	AFFECT_NOG_ABILITY = 302,
	
	AFFECT_DG_ABILITY = 303,

#ifdef ENABLE_WOLFMAN_CHARACTER
	AFFECT_BLEEDING = 320,
	AFFECT_RED_POSSESION = 174,
	AFFECT_BLUE_POSSESION = 175,
#endif
#ifdef ENABLE_ATTENDANCE_EVENT
	AFFECT_EXP_BONUS_EVENT = 557,
	AFFECT_ATT_SPEED_SLOW = 558,
#endif

#ifdef ENABLE_SHOP_DECORATION_SYSTEM
	AFFECT_SHOP_DECO = 559,
#endif

#ifdef ENABLE_AUTO_HUNTING_SYSTEM
	AFFECT_AUTO_HUNT = 560,
#endif

#ifdef ENABLE_KING_GUILD_SYSTEM
	AFFECT_KING_GUILD = 561,
#endif

#if defined(ENABLE_BATTLE_ZONE_SYSTEM)
	AFFECT_COMBAT_ZONE_POTION = 585,
	AFFECT_COMBAT_ZONE_DEFENSE = 586,
	AFFECT_COMBAT_ZONE_MOVEMENT = 587,
#endif

#ifdef ENABLE_MELEY_LAIR_DUNGEON
	AFFECT_STATUE = 700,
#endif

#ifdef ENABLE_AFK_MODE_SYSTEM
	AFFECT_AFK = 902,
#endif

#ifdef ENABLE_VALUE_PACK_SYSTEM
	AFFECT_PREMIUM = 903,
	AFFECT_PREMIUM2 = 904,
	AFFECT_PREMIUM3 = 905,
#endif

#ifdef ENABLE_ITEM_SOUL_SYSTEM
	AFFECT_SOUL = 910,
#endif

#ifdef ENABLE_ALIGNMENT_SYSTEM
	AFFECT_ALIGN_BONUS1 = 920,
	AFFECT_ALIGN_BONUS2 = 921,
	AFFECT_ALIGN_BONUS3 = 922,
#endif

#ifdef ENABLE_BLEND_ICON_SYSTEM
	AFFECT_POTION_1 = 350,
	AFFECT_POTION_2 = 351,
	AFFECT_POTION_3 = 352,
	AFFECT_POTION_4 = 353,
	AFFECT_POTION_5 = 354,
	AFFECT_POTION_6 = 355,
	AFFECT_POTION_7 = 356,
	AFFECT_POTION_8 = 357,
	AFFECT_POTION_9 = 358,
	AFFECT_POTION_10 = 359,
	AFFECT_POTION_11 = 360,
	AFFECT_POTION_12= 361,
	AFFECT_POTION_13 = 362,
#endif

#ifdef ENABLE_PERMA_BLEND_SYSTEM
	AFFECT_18385 = 363,
	AFFECT_18386 = 364,
	AFFECT_18387 = 365,
	AFFECT_18388 = 366,
	AFFECT_18389 = 367,
	AFFECT_18390 = 368,
	AFFECT_18391 = 369, // Kýrmýzý // Kritik
	AFFECT_18392 = 370, // Turuncu // Delici
	AFFECT_18393 = 371, // Sarý // Saldýrý Hýzý
	AFFECT_18394 = 372, // Yeþil // Büyüye karþý dayanýklýlýk
	AFFECT_18395 = 373, // Mavi // Saldýrý Degeri
	AFFECT_13131 = 374, // Beyaz // Savunma
#endif

	AFFECT_QUEST_START_IDX = 1000
};

enum EAffectBits
{
	AFF_NONE,

	AFF_YMIR,
	AFF_INVISIBILITY,
	AFF_SPAWN,

	AFF_POISON,
	AFF_SLOW,
	AFF_STUN,

	AFF_DUNGEON_READY,		// ´øÀü¿¡¼­ ÁØºñ »óÅÂ
	AFF_DUNGEON_UNIQUE,		// ´øÀü À¯´ÏÅ© (Å¬¶óÀÌ¾ðÆ®¿¡¼­ ÄÃ¸µµÇÁö¾ÊÀ½)

	AFF_BUILDING_CONSTRUCTION_SMALL,
	AFF_BUILDING_CONSTRUCTION_LARGE,
	AFF_BUILDING_UPGRADE,

	AFF_MOV_SPEED_POTION,
	AFF_ATT_SPEED_POTION,

	AFF_FISH_MIND,
	AFF_JEONGWIHON,		// Àü±ÍÈ¥
	AFF_GEOMGYEONG,		// °Ë°æ
	AFF_CHEONGEUN,		// Ãµ±ÙÃß
	AFF_GYEONGGONG,		// °æ°ø¼ú
	AFF_EUNHYUNG,		// ÀºÇü¹ý
	AFF_GWIGUM,			// ±Í°Ë
	AFF_TERROR,			// °øÆ÷
	AFF_JUMAGAP,		// ÁÖ¸¶°©
	AFF_HOSIN,			// È£½Å
	AFF_BOHO,			// º¸È£
	AFF_KWAESOK,		// Äè¼Ó
	AFF_MANASHIELD,		// ¸¶³ª½¯µå
	AFF_MUYEONG,		// ¹«¿µÁø affect
	AFF_REVIVE_INVISIBLE,	// ºÎÈ°½Ã Àá½Ãµ¿¾È ¹«Àû
	AFF_FIRE,			// Áö¼Ó ºÒ µ¥¹ÌÁö
	AFF_GICHEON,		// ±âÃµ´ë°ø
	AFF_JEUNGRYEOK,		// Áõ·Â¼ú
	AFF_TANHWAN_DASH,		// ÅºÈ¯°Ý¿ë ´Þ¸®±â¾îÆåÆ®
	AFF_PABEOP,			// ÆÄ¹ý¼ú
	AFF_CHEONGEUN_WITH_FALL,	// Ãµ±ÙÃß
	AFF_POLYMORPH,
	AFF_WAR_FLAG1,
	AFF_WAR_FLAG2,
	AFF_WAR_FLAG3,

	AFF_CHINA_FIREWORK,
	AFF_HAIR,	// Çì¾î
	AFF_GERMANY, // µ¶ÀÏ
	AFF_UNIQUE,
#ifdef ENABLE_WOLFMAN_CHARACTER
	AFF_BLEEDING,			// 42
	AFF_RED_POSSESSION,		// 44
	AFF_BLUE_POSSESSION,	// 43
#endif

#ifdef ENABLE_MELEY_LAIR_DUNGEON
	AFF_STATUE1,
	AFF_STATUE2,
	AFF_STATUE3,
	AFF_STATUE4,
#endif

#ifdef ENABLE_YOUTUBER_SYSTEM
	AFF_YOUTUBER,
	AFF_TWITCH,
#endif

#ifdef ENABLE_DRAGON_SOUL_ACTIVE_EFFECT
	AFF_DRAGON_SOUL,
#endif

#ifdef ENABLE_WIND_SHOES_RENEWAL
	AFF_WIND_SHOES,
#endif

#ifdef ENABLE_AFK_MODE_SYSTEM
	AFF_AFK,
#endif

#ifdef ENABLE_VALUE_PACK_SYSTEM
	AFF_PREMIUM,
#endif

#ifdef ENABLE_ITEM_SOUL_SYSTEM
	AFF_RED_SOUL,
	AFF_BLUE_SOUL,
	AFF_MIX_SOUL,
#endif

#ifdef ENABLE_KING_GUILD_SYSTEM
	AFF_KING_GUILD,
#endif

	AFF_BITS_MAX
};

extern void SendAffectAddPacket(LPDESC d, CAffect* pkAff);

// AFFECT_DURATION_BUG_FIX
enum AffectVariable
{
	// Affect°¡ ¹«ÇÑ´ë·Î µé¾î°¡ ÀÖ¾î¾ß ÇÒ °æ¿ì »ç¿ë.
	// ½Ã°£À» °è¼Ó ÁÙÀÌ±â ¶§¹®¿¡ ¸Å¿ì Å«°ªÀ¸·Î ¹«ÇÑ´ë¸¦ ¿¡¹Ä·¹ÀÌ¼ÇÇÔ.
	//// 24ºñÆ®´Â ÀûÀ¸¹Ç·Î 25ºñÆ®¸¦ »ç¿ë.
	// ... 25ºñÆ® »ç¿ëÇÑ´Ù°í ÇØ³õ°í¼± 29bit »ç¿ëÇÏ°í ÀÖ´Â ¾öÃ»³­ ÁÖ¼®ÀÌ¶õ...
	// collect quest¿¡¼­ ¹«ÇÑ ½Ã°£À» 60³âÀ¸·Î »ç¿ëÇÏ°í ÀÖÀ¸¹Ç·Î, ¿©±âµµ 60³âÀ¸·Î ÇÏÀÚ.

	INFINITE_AFFECT_DURATION = 60 * 365 * 24 * 60 * 60
};
// END_AFFECT_DURATION_BUG_FIX

#endif
