say_title ( mob_name ( 20406 ) ) 
say ( "" ) 
say ( "Yansýtma sistemi ekipmanlarýnýzýn görünüþünü " ) 
say ( "kalýcý olarak deðiþtirmeye yarar. Yansýttýðýnýz ekipman" ) 
say ( "ekipmanýnýzýn seviyesinden yüksek olsa bile," ) 
say ( "görüþünü deðiþtirir." ) 
say ( "Devam etmek istiyor musun?" ) 
say ( "" ) 
local confirm = select ( "Evet" , "Hayýr" ) 
if confirm == 2 then 
return 
end 
setskin ( NOWINDOW ) 
pc . open_changelook ( true , false ) 
