say ( "Bu bitkiler (1) Hasun Zindanýndan toplandý. " ) 
say ( "Atýný tekrar canlandýracaklar. " ) 
say ( "Haydi atýný çaðýralým! " ) 
wait ( ) 
say ( "Ata bitkileri yedir ve bekle. " ) 
say ( "[DELAY value=400]. . .[/DELAY]" ) 
horse . summon ( ) 
wait ( ) 
say ( "Atýn canlanmaya baþladý. " ) 
say ( "Gelecekte atýný beslemeyi unutma. " ) 
if pc . countitem ( "50057" ) >= 1 then 
pc . removeitem ( "50057" , 1 ) 
horse . revive ( ) 
end 
