#ifndef __INC_PYTHON_rootlib_MANAGER_H__
#define __INC_PYTHON_rootlib_MANAGER_H__
#include "Locale_inc.h"
#define initrootlibManager initrootlib
/* rootlib module */
/* rootlib.isExist */
/* rootlib.moduleImport */
/* rootlib.getList */
/* this lib includes modules under this lines.
	colorInfo
	consoleModule
	constInfo
	cpyshield
	debugInfo
	dragon_soul_refine_settings
	eigenmods
	emotion
	exception
	game
	grid
	interfaceModule
	introCreate
	introEmpire
	introLoading
	introLogin
	intrologin_ex
	intrologin_old
	introLogo
	introSelect
	localeInfo
	main
	mouseModule
	musicInfo
	networkModule
	new_introcreate
	new_introselect
	playerSettingModule
	Prototype
	rare_settings
	select_assassinskills
	select_shamanskills
	select_suraskills
	select_warriorskills
	select_wolfmanskills
	serverCommandParser
	serverInfo
	stringCommander
	svsideoi
	switchbot
	test_affect
	translate
	ui
	ui12zi
	uiAffectShower
	uiAttachMetin
	uiaura
	uiautohunt
	uiaverage_price
	uibiowindow
	uibiyolog
	uibkoku
	uibosstracking
	uicards
	uichangelook
	uiCharacter
	uicharacterdetails
	uiChat
	uichequeticket
	uichestdrop
	uicombatzone
	uiCommon
	uiCube
	uicube_ex
	uiDragonSoul
	uidungeoninfo
	uiEquipmentDialog
	uievent
	uiEx
	uiExchange
	uiGameButton
	uiGameOption
	uigameoption_old
	uigemshop
	uigift
	uiGuild
	uiHelp
	uiInventory
	uiitemcombination
	uiitempreview
	uikeyboard
	uikeyboardsettings
	uiluckybox
	uimailbox
	uiMapNameShower
	uimeleylairranking
	uiMessenger
	uiminigame
	uiminigameattendance
	uiminigamecatchking
	uiminigamefishevent
	uiMiniMap
	uinewplayergauge
	uinewshop
	uinpcekran
	uiOption
	uiParty
	uipetfeed
	uipetincubatrice
	uipetsystem
	uiPhaseCurtain
	uiPickMoney
	uiPlayerGauge
	uiPointReset
	uiPrivateShopBuilder
	uiprivateshopsearch
	uiQuest
	uirarityrefine
	uiredgemshop
	uiRefine
	uiRestart
	uiruhtasi
	uiSafebox
	uisash
	uiScriptLocale
	uiselectitem
	uiselectitemex
	uiSelectMusic
	uiShop
	uisupportshaman
	uiSystem
	uiSystemOption
	uiTarget
	uiTaskBar
	uiTip
	uiToolTip
	uiUploadMark
	uiutils
	uiWeb
	uiWhisper
	uiyoutube
	uiyoutubefavlist
	uiyoutuber
	ui_wrapper
*/
#ifdef __USE_CYTHON__
void initrootlibManager();
#endif
#endif
